[[questions]]
question = "В каком году рабочий посёлок Красногорск был преобразован в город?"
answers = ["1940"]
alternatives = ["1850", "1926", "1932"]

[[questions]]
question = "Назовите год рождения легендарного дуба?"
answers = ["1745"]
alternatives = ["1812", "1630", "1910"]

[[questions]]
question = "На территории храма Знамение Божией Матери г. Красногорска находится часовня-усыпальница. Кому она принадлежала?"
answers = ["Поляковым"]
alternatives = [
    "Юсуповым",
    "Волынским",
    "Долгоруким",
]

[[questions]]
question = "Силами каких военнопленных в 1947-1949г.г. было построено здание РГАКФД?"
answers = ["японских"]
alternatives = ["немецких", "румынских", "венгерских"]

[[questions]]
question = "Кто был инициатором создания Мемориального музея немецких антифашистов?"
answers = ["руководство ГДР"]
alternatives = [
    "местные жители",
    "СССР",
    "участники немецкого Сопротивления",
]

[[questions]]
question = "В каком году был основан Красногорский завод имени С. А. Зверева?"
answers = ["1942"]
alternatives = ["1927", "1932", "1940"]

[[questions]]
question = "Что изображено на логотипе Красногорского завода имени С. А. Зверева?"
answers = ["призма Дове со стрелкой"]
alternatives = [
    "пентапризма",
    "линза",
    "лупа",
]

[[questions]]
question = "Около проходной завода находится скульптура «Юный фотограф». Что изображает пьедестал скульптуры?"
answers = ["линза"]
alternatives = [
    "объектив",
    "призма",
    "лупа",
]

[[questions]]
question = "На яблоневой аллее в г. Красногорске находится памятник фронтовому кинооператору. Кто стал прототипом памятника?"
answers = ["В. Сущинский"]
alternatives = ["Р.Кармен", "С. Школьников", "собирательный образ"]

[[questions]]
question = "Какой Болгарский город побратим г. Красногорску?"
answers = ["Сливница"]
alternatives = ["Радомир", "Славяново", "Златица"]